[main]
font=FiraCode Nerd Font Mono:weight=light:size=12
use-bold=no

dpi-aware=yes

placeholder=""
prompt="  "

# icon-theme=Papirus-Dark
icon-theme=Tela-circle-black-dark
icons-enabled=true

show-actions = no

lines = 10
minimal-lines=yes

width = 48

horizontal-pad = 12
vertical-pad = 8
inner-pad = 8

# 1 is disabled
image-size-ratio=1

[colors]
background=121212e5
text=c0c0c0ff
prompt=c0c0c0ff
placeholder=c0c0c0aa
input=c0c0c0ff
match=993e36ff
selection=323232ff
selection-text=ffffffff
selection-match=cf4f43ff
counter=00ff00ff
border=aeaeaeff

[border]
width=1
radius=0
selection-radius=0

[border]
width=2
radius=8

[dmenu]
exit-immediately-if-empty=no

[key-bindings]
cancel=Control+c Control+q Escape
# Free up ctrl+k
delete-line-forward=none
delete-line-backward=none
delete-next=none

first=Control+g
last=Control+Shift+g

prev=Control+k Up
next=Control+j Down

prev-page=Control+u
next-page=Control+d
