# --- Fonts ---
font=FiraCode Nerd Font Mono:size=12

# --- Window / padding ---
pad=8x2 center
bold-text-in-bright=no

# --- Colors ---
[colors-dark]
background=101010
foreground=e0e0e0
alpha=0.9

selection-background=323232
selection-foreground=e0e0e0

cursor=101010 aeaeae

# ANSI normal (0–7)
regular0=080808
regular1=cf4f43
regular2=54964f
regular3=d17536
regular4=1b4666
regular5=5e196d
regular6=049191
regular7=646464

# ANSI bright (8–15)
bright0=323232
bright1=993e36
bright2=5c8b59
bright3=aa9c30
bright4=1267a5
bright5=8910ad
bright6=01a8a8
bright7=f5f5f5

[scrollback]
lines=10000
multiplier=3.0
indicator-position=relative
indicator-format=percentage

[url]
osc8-underline=always
